### ISSUE TITLE
Add title indicator for new events

### ISSUE THREAD

**Issue by kelunik** [beberlei/php-rfc-watch#12]
Add something like `(1)`, ..., `(n)` to the page title to indicate new events since that tab has been active.
Implementation should use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API).

**Comment by beberlei** [comment]
Yeah, i would like this myself, need to figure out how to do this sanely.

**Comment by kelunik** [comment]
How does refreshing currently work?

**Comment by beberlei** [comment]
@kelunik There is a setInterval() called every 60 seconds in app.jsx that triggers a refresh on the EventsStore.

**Comment by kelunik** [comment]
If we have event IDs, we could just store the last event ID the user saw and use `currentId - lastSeenId` for the number of new events. However, we have to filter hidden RFCs.

**Comment by beberlei** [comment]
IDs are UUIDs, so thats not going to work, but you can easily check the number of events before and after each refresh (filtered for visible yes/no).
