### ISSUE TITLE
Future Post Dates

### ISSUE THREAD

**Issue by drobinson** [beberlei/php-rfc-watch#14]
Either this tool now predicts the future (awesome) or the timezone friendly display isn't quite right.
![screenshot 2015-03-02 09 15 53](https://cloud.githubusercontent.com/assets/455332/6446006/f6f3395a-c0bc-11e4-8e11-346441caf7da.png)

**Comment by rdohms** [comment]
@beberlei mentioned that this was an issue with the wiki and its own setup.

**Comment by beberlei** [comment]
we grab the unix timestamps from images from the wiki server and use them as our own. So if the clocks are not synced or they use a different timezone (both is likeli) then this will occur.

**Comment by kelunik** [comment]
php.net doesn't provide unix timestamps. Dates provided in the image `title` are in `UTC + 1`.

**Comment by svivian** [comment]
Yes everything is happening "in 1 hour" for me. If the wiki's times are UTC+1 can't you just subtract an hour and use that?
