### ISSUE TITLE
Doesn't show all votes when there are multiple votes in one RFC

### ISSUE THREAD

**Issue by michaelcullum** [beberlei/php-rfc-watch#20]
Such as https://wiki.php.net/rfc/reserve_even_more_types_in_php_7#vote

**Comment by beberlei** [comment]
Yes, but not worth fixing imho.

**Comment by Nessworthy** [comment]
I disagree. https://wiki.php.net/rfc/same-site-cookie On the site it shows this RFC as a 100% vote no, but the RFC has a second vote for an alternate implementation, which passed.

**Comment by stof** [comment]
@beberlei this is now fixed
