### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by rob006** [beberlei/php-rfc-watch#26]
This will be really helpful for watching changes on website. Right now last change was 2 months ago - it is easy to forget about the whole project if you need to visit it manually every time to see that nothing has changed since last visit.

**Comment by stof** [comment]
@beberlei isn't it already available ?

**Comment by rob006** [comment]
There is a RSS feed available, but it only contains finished votes, so:

1. It does not inform about new content on website.
2. It cannot be used to watch RFC status (new vote for RFC).

**Comment by janvernieuwe** [comment]
The current feed has a 500 error too :\

**Comment by beberlei** [comment]
fixed the 500, works now from https://php-rfc-watch.beberlei.de/atom.xml
