### ISSUE TITLE
Zombie votes appear in the UI when they are renamed in the PHP RFC

### ISSUE THREAD

**Issue by stof** [beberlei/php-rfc-watch#43]
The RFC https://wiki.php.net/rfc/concatenation_precedence only has 2 votes.

But https://php-rfc-watch.beberlei.de/ displays a third one for the block rendering `Change the precedence of the concatenation operator` (with only 2 votes casted).
Based on the history of the wiki page (see https://wiki.php.net/rfc/concatenation_precedence?rev=1556663802&do=diff), the vote was renamed. And your DB seems to have kept the old name around as well (and number of votes are wrong for the new vote btw).

**Comment by beberlei** [comment]
Fixed via admin screen that allows disabling individual questions of an RFC vote.
