### ISSUE TITLE
Sort voting options

### ISSUE THREAD

**Issue by Seldaek** [beberlei/php-rfc-watch#6]
Some RFCs have Yes/No and some No/Yes which kinda tripped me up while scanning results.. I guess doing any kind of consistent sorting would be a plus, but ideally having Yes first would be great as it's usually like that on the wiki.

**Comment by Seldaek** [comment]
Just saw the result bars now.. and it makes it even more important I think, because e.g. the pecl_http vote is a huge green bar while that green part is actually the No votes, kinda confusing :)

**Comment by beberlei** [comment]
Heh yeah, that needs improvement.

**Comment by beberlei** [comment]
fixed

**Comment by Seldaek** [comment]
Looking good! Thanks :)
